name:           Hadron
version:        1.0
author:         Florent Lioult
maintainer:     florent@hihan.org

dependencies:
- base
- array
- GPipe == 2.3.1
- GPipe-GLFW == 1.4.2.0
- lens
- JuicyPixels
- linear
- containers
- ObjectName
- StateVar
- filepath
- hslogger
- mtl
- random
- text
- bytestring
- regex-compat
- time
- vector
- freetype2
- parallel
- rosezipper == 0.1
- exception-transformers

executables:
  Hadron:
    source-dirs:         src
    main:                Main.hs
    ghc-options:
    - -j4
    - -threaded
