resolver: lts-18.28

packages:
- '.'
- '../GPipe-Core/GPipe-Core'
- '../GPipe-GLFW/GPipe-GLFW'
- '../dear-imgui.hs'

flags:
  dear-imgui:
    glfw: true
    opengl2: true

extra-deps:
- rosezipper-0.1
